### ISSUE TITLE
Getting 400 http status

### ISSUE THREAD

**Issue by ymai** [attm2x/m2x-java#4]
Below is the tcp stream capture from wireshark

>PUT /v2/devices/14449e222ec2d06f0be8cb377bca3350/streams/humidity/value HTTP/1.1
>X-M2X-KEY: 405f57a443495eeea37c126b2eaaa8d9
>User-Agent: M2X-Java/2.0.0 java/1.7.0_25 (x86_64-Mac OS X10.9.5)
>Content-Type: application/json
>Host: api-m2x.att.com
>Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
>Connection: keep-alive
>Content-Length: 14

>{"value":"55"}HTTP/1.1 400 Bad Request
>Server: nginx
>Date: Wed, 11 Feb 2015 00:29:06 GMT
>Content-Type: application/json
>Content-Length: 47
>Status: 400 Bad Request
>X-M2X-VERSION: v2.8.1-alpha
>Vary: Accept-Encoding
>
{>"message":"Invalid header value: \"*; q=.2\""}

I went to test this with curl the following curl and it works.

>curl -i -X PUT http://api-m2x.att.com/v2/devices/14449e222ec2d06f0be8cb377bca3350/streams/humidity/value -H "X-M2X-KEY: 405f57a443495eeea37c126b2eaaa8d9" -H "Content-Type: application/json" -d '{ "value": "40" }'
>HTTP/1.1 202 Accepted
>Server: nginx
>Date: Wed, 11 Feb 2015 14:41:45 GMT
>Content-Type: application/json
>Content-Length: 21
>Status: 202 Accepted
>X-M2X-VERSION: v2.8.1-alpha
>Vary: Accept-Encoding
 
But if I had the Accept Header, it does not work
>curl -i -X PUT http://api-m2x.att.com/v2/devices/14449e222ec2d06f0be8cb377bca3350/streams/humidity/value -H "X-M2X-KEY: 405f57a443495eeea37c126b2eaaa8d9" -H "Content-Type: application/json" -H "Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" -d '{ "value": "40" }'
>HTTP/1.1 400 Bad Request
>Server: nginx
>Date: Wed, 11 Feb 2015 14:34:54 GMT
>Content-Type: application/json
>Content-Length: 47
>Status: 400 Bad Request
>X-M2X-VERSION: v2.8.1-alpha
>Vary: Accept-Encoding

From the M2XResponse class, it seems that it did not set the Accept header on the HttpURLConnection object.

Since this is interacting with RESTful WS, my guess is the accept value should be set to "application/json".

**Comment by inkel** [comment]
@ymai thank you for your report. We've fixed this in [`2.0.1`](https://github.com/attm2x/m2x-java/releases/tag/2.0.1), which was released two days ago. Please update your library and let us know if you continue to have problems with it.

**Comment by ymai** [comment]
Arrgh.  Miss it by one day.  Thanks for the update.

**Comment by inkel** [comment]
Thank you fir the report, @ymai!
