### ISSUE TITLE
Add Support for Device Metadata Endpoints


### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-java#8]
Add support for the following endpoints:

* https://m2x.att.com/developer/documentation/v2/device#Read-Device-Metadata
* https://m2x.att.com/developer/documentation/v2/device#Update-Device-Metadata
* https://m2x.att.com/developer/documentation/v2/device#Read-Device-Metadata-Field
* https://m2x.att.com/developer/documentation/v2/device#Update-Device-Metadata-Field

**Comment by fsaravia** [comment]
This is already supported by the [`M2XClassWithMetadata `](https://github.com/attm2x/m2x-java/blob/master/src/main/java/com/att/m2x/java/M2XClassWithMetadata.java) class.
